# Based on https://github.com/felixduvallet/ros-travis-integration
#
# vim:set ts=2 sw=2 et:
dist: xenial
sudo: required
language: generic
compiler:
  - gcc
cache:
  directories:
    - $HOME/.cache/pip
  before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
cache:
  - apt

env:
  global:
    - ROS_CI_DESKTOP="$(lsb_release -cs)"
    - CI_SOURCE_PATH=$(pwd)
    - ROS_DISTRO=kinetic

before_install:
  - sudo sh -c "echo \"deb http://packages.ros.org/ros/ubuntu $ROS_CI_DESKTOP main\" > /etc/apt/sources.list.d/ros-latest.list"
  - sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential git valgrind
  - sudo apt-get install -y python-rosinstall python-rosinstall-generator python-wstool python-catkin-tools
  # Install clang-format 3.8
  - sudo apt-get install -y clang-format-3.8
  # Install ROS Kinetic
  - sudo apt-get install -y ros-$ROS_DISTRO-ros-base
  # Install yaml-cpp ROS package
  - sudo apt-get install -y libyaml-cpp-dev
  # Install MavLink and Mavros
  - sudo apt-get install -y ros-$ROS_DISTRO-mavlink ros-$ROS_DISTRO-mavros-msgs ros-$ROS_DISTRO-mavros ros-$ROS_DISTRO-mavros-extras
  # Source environment
  - source /opt/ros/$ROS_DISTRO/setup.bash
  # Prepare rosdep
  - sudo rosdep init
  - rosdep update

install:
  # Create catkin workspace
  - mkdir -p ~/catkin_ws
  - cd ~/catkin_ws
  - catkin config --init --mkdirs
  # Pull source depends
  - cd src
  - wstool init
  # Link the repository we are testing to the new workspace
  - ln -s $CI_SOURCE_PATH .
  # Install dependency
  - cd ~/catkin_ws
  - rosdep install --from-paths src --ignore-src --rosdistro $ROS_DISTRO -q -y
  # Install GeographicLib datasets
  - sudo -H mkdir -p /usr/share/geographiclib
  - wget https://raw.githubusercontent.com/mavlink/mavros/master/mavros/scripts/install_geographiclib_datasets.sh
  - chmod +x install_geographiclib_datasets.sh
  - sudo -H ./install_geographiclib_datasets.sh

before_script:
  # Source environment
  - source /opt/ros/$ROS_DISTRO/setup.bash

script:
  - set -e
  - cd ~/catkin_ws
  - catkin build
  - source ~/catkin_ws/devel/setup.bash
  # Check for clang format
  - cd src/avoidance
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  - ./check_code_format.sh
  - catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release -DCATKIN_ENABLE_TESTING=False -DDISABLE_SIMULATION=ON && catkin build
  - catkin config --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCATKIN_ENABLE_TESTING=True && catkin build avoidance local_planner global_planner safe_landing_planner --no-deps -v -i --catkin-make-args tests
  - status=0 && for f in ~/catkin_ws/devel/lib/*/*-test; do valgrind --leak-check=full --track-origins=yes --error-exitcode=1 $f || status=1; done
  - (roscore &) && for f in ~/catkin_ws/devel/lib/*/*-test-roscore; do valgrind --leak-check=full --track-origins=yes --error-exitcode=1 --suppressions=local_planner/test/valgrind_suppressions.sup $f || status=1; done && exit $status
