
name: Check Format
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: px4io/px4-dev-ros-kinetic:2019-10-24
    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: check_format
      working-directory: tools
      run: |
        apt update
        apt install -y clang-format-3.8
        ./check_code_format.sh